ad_envs_args:
  n_processes: 10
  use_heldout_tasks: false
adpp_args:
  n_actions: 5
adpp_envs_args:
  n_processes: 10
  use_heldout_tasks: true
data_args:
  alpha: 0.5
  dense_reward: false
  grid_world_args:
    absorbing_state: true
    atol: 0.2
    gamma: 0.99
    seed: ${seed}
    terminate_on_goal: false
  heldout_tasks: [[0, 0]]
  include_goal: false
  mask_nonactions: false
  n_data: 100_000
  n_episodes: 1
  steps_per_context: ${model_args.steps_per_context}
  value_iteration_args:
    n_policies: ${data_args.n_data}
  yield_every: 1
data_path: grid_world/ad
decay_args:
  final: 100_000
  warmup: 1000
dummy_vec_env: false
evaluate_args:
  gamma: ${data_args.grid_world_args.gamma}
  n_plots: 3
grad_norm_clip: 1.0
load_path: null
log_interval: 20
log_tables_interval: 5
lr: 0.001
metrics_args: {}
model_args:
  gpt2_args:
    n_head: 4
    n_layer: 4
  n_embd: 32
  steps_per_context: 100
n_batch: 50
n_epochs: 2
save_interval: 400
seed: 0
test_ad_interval: 25
test_adpp_interval: null
weights_args:
  actions: 5
