config = dict(
    data_args=dict(
        grid_size=3,
    ),
    grad_norm_clip=1.0,
    n_batch=50,
    n_epochs=20,
    log_freq=20,
    metrics_args=dict(
        graphs_per_component=7,
    ),
    model_args=dict(
        layer_args=dict(
            causal_self_attention_args=dict(
                attn_pdrop=0.1,
                n_head=4,
            ),
            resid_pdrop=0.1,
        ),
        embd_pdrop=0.1,
        n_embd=32,
        n_layer=4,
        steps_per_context=50,
        action_weight=5,
        reward_weight=1,
        value_weight=1,
    ),
    optimizer_config=dict(
        betas=(0.9, 0.95),
        lr=0.001,
        weight_decay=0.1,
    ),
    n_steps=1000000,
    run_name="trial",
    save_freq=400,
    seed=0,
    test_split=0.02,
    test_freq=100,
    weights_args=dict(
        actions=5,
        rewards=1,
        # values=1,
    ),
)
