config = dict(
    data_args=dict(
        grid_size=3,
    ),
    n_batch=50,
    n_epochs=20,
    log_freq=20,
    lr=0.001,
    model_args=dict(
        action_weight=5,
        layer_args=dict(
            causal_self_attention_args=dict(
                attn_pdrop=0.1,
                n_head=4,
            ),
            resid_pdrop=0.1,
        ),
        embd_pdrop=0.1,
        n_embd=32,
        n_layer=4,
        reward_weight=1,
        steps_per_context=50,
        value_weight=1,
    ),
    n_steps=1000000,
    run_name="trial",
    save_freq=400,
    seed=0,
    test_split=0.02,
    test_freq=100,
)
